### View camera intrinsic

In [1]:
import numpy as np

row = 11
dataset_name = 'sl2'

dataset_path = '/home/ec2-user/SageMaker/raw_data/' + dataset_name + '/'
base_path = dataset_path + 'calibration_data/'

intrinsics = np.load(base_path + 'cam_mtx_list.npy')#[:1]
extrinsics = np.load(base_path + 'cam_extrinsics.npy')#[:1]
locations = np.load(base_path + 'cam_locations.npy')#[:1]
print(f'Intrinsics have shape: {intrinsics.shape}')
print(f'Extrinsics have shape: {extrinsics.shape}')
print(f'Locations have shape: {locations.shape}')

# Eventually, we can do everything in a vectorized way, but for now, to make things simple,
# lets break apart each matrix
# intrinsics = [intr for intr in intrinsics]
# extrinsics = [ext for ext in extrinsics]
# locations = [loc for loc in locations]

# cxy_list = []
# for row in range(27):
#     intr = intrinsics[row]
#     cx = 3000 - int(intr[0,2])
#     cy = 2000 - int(intr[1,2])
#     cxy_list.append((cx,cy))
# print('(cx,cy) values (rounded)\n', cxy_list)
print(intrinsics[0])


Intrinsics have shape: (27, 3, 3)
Extrinsics have shape: (3240, 4, 4)
Locations have shape: (3240, 3)
[[7.91104990e+03 0.00000000e+00 2.92599093e+03]
 [0.00000000e+00 7.91196350e+03 2.00598039e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


In [4]:
import imageio
import numpy as np
import matplotlib.pyplot as plt
img = imageio.imread("/home/ec2-user/SageMaker/raw_data/sl2/white/201030034508_0026_0119.jpg")
y = img.reshape((2000, 2, 3000, 2, 3)).mean(3).mean(1).astype(np.uint8)
%timeit z = np.multiply((1./255), y, dtype=np.float32)
# plt.imshow(y)
# plt.show()


20.4 ms ± 295 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [14]:
import numpy as np
%timeit np.zeros((4000, 6000, 3, 500), dtype=np.uint8)

14.8 µs ± 77.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
